<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $threeDaysAgo = Carbon::now()->subDays(3);
        $aWeekAgo = Carbon::now()->subWeek();
        $twoWeeksAgo = Carbon::now()->subWeek();
        $aMonthAgo = Carbon::now()->subMonth();

        $products = [
            [
                'product_id' => 'P002',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-1.jpg',
                'name' => 'product 1',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P003',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-2.jpg',
                'name' => 'product 2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P004',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-3.jpg',
                'name' => 'product 3',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P005',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-4.jpg',
                'name' => 'product 4',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $twoWeeksAgo,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-5.jpg',
                'name' => 'product 5',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-6.jpg',
                'name' => 'product 6',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-7.jpg',
                'name' => 'product 7',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-8.jpg',
                'name' => 'product 8',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-9.jpg',
                'name' => 'product 9',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-10.jpg',
                'name' => 'product 10',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-11.jpg',
                'name' => 'product 11',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-12.jpg',
                'name' => 'product 12',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-13.jpg',
                'name' => 'product 13',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-14.jpg',
                'name' => 'product 14',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-15.jpg',
                'name' => 'product 15',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '10',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-16.jpg',
                'name' => 'product 16',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '10',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-17.jpg',
                'name' => 'product 17',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '10',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-18.jpg',
                'name' => 'product 18',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'product-19.jpg',
                'name' => 'product 19',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            
        ];

        // Insert data into the products table
        DB::table('products')->insert($products);
    }

    
}
